"""Tests for node2node issues"""

from django.urls import reverse

from rest_framework import status

from core.utils.testing_utils import Node2NodeReceptionTestCase

from comments.models import Comment

import requests

import json


class TestNode2NodeComments(Node2NodeReceptionTestCase):
    def setUp(self) -> None:
        super().setUp()
        # create a user and a post to comment on
        self.initialize_sample_authors(1)
        self.initialize_sample_text_posts(1)

        # initialize other node only once local stuff is done so the tests don't wait forever to timeout a localhost:10000 call
        self.initialize_other_node()

        self.initialize_external_authors(1)

        self.author0_inbox_url = self.live_server_url + reverse("user_management:node2node_inbox", args=[
            self.sample_authors[0].get_encoded_fqid()
        ])

    # @override_settings(DEBUG=True)

    def test_create_comment_via_json(self) -> None:
        """Simulate receiving a comment via node2node"""
        post = self.sample_posts[0][0]
        external_author = self.external_authors[0]

        receive_json = {
            "type": "comment",
            "author": {
                "type": "author",
                "id": external_author.fqid,
                "host": self.other_node.host_url,
                "displayName": external_author.display_name,
                "profileImage": "",
                "page": "http://localhost:10000/api/authors/3f3c2376-c0eb-401e-abd9-3a1ab6c5cfca",  # This shouldn't matter?
            },
            "comment": "hello",
            "contentType": "text/plain",
            "published": "2025-03-29T22:22:35.342617+00:00",
            # ID is generated by the remote node
            "id": "http://localhost:10000/apicomments/5f4b580c-bd90-4ba1-a132-3826d3d50dec",
            "post": post.fqid,
            "likes": []
        }
        receive_json_string = json.dumps(receive_json)
        # this is a little bit brittle, if requests gets changed in Node.send_create, etc it will need a rework
        # simulate receiving the commend via node2node
        response = requests.post(self.author0_inbox_url, data=receive_json_string, headers={"Content-Type": "application/json"},
                                 auth=(self.other_node_user.username, "node"))
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Comment.objects.count(), 1)

    def test_create_comment_via_json_unauthorized(self) -> None:
        """Simulate receiving a comment via node2node by no user, and by a user with a bad password"""
        # do the same as above, but with a bad authentication header
        post = self.sample_posts[0][0]
        external_author = self.external_authors[0]

        receive_json = {
            "type": "comment",
            "author": {
                "type": "author",
                "id": external_author.fqid,
                "host": self.other_node.host_url,
                "displayName": external_author.display_name,
                "profileImage": "",
                "page": "http://localhost:10000/api/authors/3f3c2376-c0eb-401e-abd9-3a1ab6c5cfca",  # This shouldn't matter?
            },
            "comment": "hello",
            "contentType": "text/plain",
            "published": "2025-03-29T22:22:35.342617+00:00",
            # ID is generated by the remote node
            "id": "http://localhost:10000/apicomments/5f4b580c-bd90-4ba1-a132-3826d3d50dec",
            "post": post.fqid,
            "likes": []
        }
        receive_json_string = json.dumps(receive_json)
        # this is a little bit brittle, if requests gets changed in Node.send_create, etc it will need a rework
        # simulate receiving the commend via node2node
        response = requests.post(self.author0_inbox_url, data=receive_json_string, headers={"Content-Type": "application/json"},
                                 auth=(self.other_node_user.username, "bad_password"))
        # make sure we get a 403/401 and the comment is not created
        self.assertIn(response.status_code, [
                      status.HTTP_403_FORBIDDEN, status.HTTP_401_UNAUTHORIZED])
        self.assertEqual(Comment.objects.count(), 0)

        # try again without an auth header at all
        response = requests.post(self.author0_inbox_url, data=receive_json_string, headers={
                                 "Content-Type": "application/json"})
        # make sure we get a 403/401 and the comment is not created
        self.assertIn(response.status_code, [
                      status.HTTP_403_FORBIDDEN, status.HTTP_401_UNAUTHORIZED])
        self.assertEqual(Comment.objects.count(), 0)

    def test_create_comment_via_json_bad_format(self) -> None:
        """Simulate receiving a comment with a bad format via node2node"""
        post = self.sample_posts[0][0]
        external_author = self.external_authors[0]
        # do the same as above, but with bad json
        receive_json = {
            "type": "comment",
            "author": {
                "something": "bad"
            },
            "comment": "hello",
            "another bad": "entry",
        }
        receive_json_string = json.dumps(receive_json)
        response = requests.post(self.author0_inbox_url, data=receive_json_string, headers={"Content-Type": "application/json"},
                                 auth=(self.other_node_user.username, "node"))
        # make sure we get a 400 and the comment is not created
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertEqual(Comment.objects.count(), 0)
