"""Tests for node2node issues"""

from django.test import tag, override_settings
from django.urls import reverse

from rest_framework import status

from core.utils.testing_utils import Node2NodeTestCase

from posts.models import Post, PostTypes, VisibilityTypes
from comments.models import Comment
from user_management.models import Node, User, Author, JoinRequest

import requests

import json


@tag("node2node")
class TestNode2Node(Node2NodeTestCase):
    @override_settings(DEBUG=True)
    def test_create_comment_via_json(self) -> None:
        """Simulate receiving a commend via node2node"""
        # create a user and a post to comment on
        self.initialize_sample_authors(1)
        self.initialize_sample_text_posts(1)
        post = self.sample_posts[0][0]

        # initialize other node only once local stuff is done so the tests don't wait forever to timeout a localhost:10000 call
        self.initialize_other_node()

        self.initialize_external_authors(1)
        external_author = self.external_authors[0]

        receive_json = {
            "type": "comment",
            "author": {
                "type": "author",
                "id": external_author.get_encoded_fqid(),
                "host": self.other_node.host_url,
                "displayName": external_author.display_name,
                "profileImage": "",
                "page": "http://localhost:10000/api/authors/3f3c2376-c0eb-401e-abd9-3a1ab6c5cfca",  # This shouldn't matter?
            },
            "comment": "hello",
            "contentType": "text/plain",
            "published": "2025-03-29T22:22:35.342617+00:00",
            # ID is generated by the remote node
            "id": "http://localhost:10000/apicomments/5f4b580c-bd90-4ba1-a132-3826d3d50dec",
            "post": post.get_encoded_fqid(),
            "likes": []
        }
        receive_json_string = json.dumps(receive_json)
        # this is a little bit brittle, if requests gets changed in Node.send_create, etc it will need a rework
        # simulate receiving the commend via node2node
        my_url = self.live_server_url + reverse("comments:node2node_comments-list")
        response = requests.post(my_url, data=receive_json_string, headers={"Content-Type": "application/json"},
                                 auth=(self.other_node_user.username, "node"))
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Comment.objects.count(), 1)
