# Generated by Django 5.1.6 on 2025-03-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_author_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='page_url',
            field=models.URLField(blank=True, verbose_name='Page URL'),
        ),
    ]
