# Generated by Django 5.1.6 on 2025-03-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_author_page_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['uuid']},
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Username'),
        ),
    ]
