# Generated by Django 5.1.6 on 2025-03-20 05:11

import django.db.models.deletion
import user_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_author_options_alter_author_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user_management.models.UserManagerBase()),
                ('authors', user_management.models.AuthorUserManager()),
                ('nodes', user_management.models.ExternalNodeUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='host_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.node'),
        ),
    ]
