# Generated by Django 5.1.6 on 2025-03-19 19:19

import user_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_author_options_alter_author_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user_management.models.UserManagerBase()),
                ('authors', user_management.models.AuthorUserManager()),
                ('nodes', user_management.models.ExternalNodeUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='Is Disabled'),
        ),
    ]
