# Generated by Django 5.1.6 on 2025-03-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_alter_user_managers_node_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='host_site_url',
            field=models.URLField(blank=True, verbose_name='Site URL'),
        ),
    ]
