# Generated by Django 5.1.6 on 2025-03-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_alter_node_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_plain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Password Plain'),
        ),
    ]
