# Generated by Django 5.1.6 on 2025-03-28 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_user_password_plain'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='external_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_node_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='node',
            name='internal_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_node_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
