# Admin panel related utility functions

from typing import Callable, Optional, Any, TypeVar
from django.db.models import QuerySet, Model
from django.contrib import admin, messages
from django.http import HttpRequest

ModelT = TypeVar('ModelT', bound=Model)


def admin_action_on_queryset(
    modeladmin: admin.ModelAdmin[ModelT],
    request: HttpRequest,
    queryset: QuerySet[ModelT],
    action: Callable[[ModelT], Any],
    success_prefix: str = "Successfully operated on",
    success_level: int = messages.SUCCESS,
    failure_prefix: str = "Failed to operate on",
    failure_level: int = messages.ERROR,
    message_suffix: str = "objects",
    stringifier: Optional[Callable[[ModelT], str]] = None,
) -> tuple[list[ModelT], list[ModelT]]:
    """Perform an action on every object in the queryset
    Then display messages to the user depending on the successes and failures of the action on each object

    The messages are generated by f"{success_prefix} {len(successes)} {message_suffix}: ..."
        - ie: if success_prefix="Approved", message_suffix="requests", and there are 3 successes, the message will be "Approved 3 requests: ..."
    Failures are generated the same, but with the failure_prefix

    Args:
        modeladmin (admin.ModelAdmin): The admin.ModelAdmin instance
        request (HttpRequest): The request of the calling admin action
        queryset (QuerySet[Any]): The queryset of objects to perform the action on
        action (Callable[..., Any]): The action to perform on each object in the queryset
        success_prefix (str): The prefix to prepend to the success message. eg: "Approved". Defaults to "Successfully operated on".
        success_level (int): The level of the message to display for successes. Defaults to messages.SUCCESS.
        failure_prefix (str): The prefix to prepend to the failure message. eg: "Failed to Approve". Defaults to "Failed to operate on".
        failure_level (int): The level of the message to display for failures. Defaults to messages.ERROR.
        message_suffix (str): The suffix to append to the message. eg: "requests". Defaults to "objects".
        stringifier (Optional[Callable[[Any], str]]): A function to convert each object to a string, uses str() if None. Defaults to None.

    Retuns:
        tuple[list[Any], list[Any]]: A tuple of lists of the successful and failed objects
    """

    successes: list[str] = []
    success_objs: list[ModelT] = []
    failures: list[str] = []
    failure_objs: list[ModelT] = []
    for obj in queryset:
        try:
            action(obj)
            successes.append(str(obj) if stringifier is None else stringifier(obj))
            success_objs.append(obj)
        except Exception as e:
            obj_string = str(obj) if stringifier is None else stringifier(obj)
            failures.append(f"[{obj_string}: {e.message if hasattr(e, 'message') else str(e)}]")
            failure_objs.append(obj)
    if successes:
        modeladmin.message_user(
            request,
            f"{success_prefix} {len(successes)} {message_suffix}: {', '.join(successes)}",
            level=success_level
        )
    if failures:
        modeladmin.message_user(
            request,
            f"{failure_prefix} {len(failures)} {message_suffix}: {', '.join(failures)}",
            level=failure_level
        )
    return success_objs, failure_objs
