# Generated by Django 5.1.6 on 2025-03-02 21:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0005_hostedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteauthor',
            name='remote_username',
        ),
        migrations.AddField(
            model_name='author',
            name='display_name',
            field=models.CharField(default='Display Name', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='github_url',
            field=models.URLField(default='https://github.com'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_requests_requested', to='socialnetwork.author')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_requests_pending', to='socialnetwork.author')),
            ],
        ),
    ]
