# Generated by Django 5.1.6 on 2025-03-08 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0007_comment_postdifferentiator_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_requests_requested', to='socialnetwork.localauthor'),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_requests_pending', to='socialnetwork.localauthor'),
        ),
    ]
