# Generated by Django 5.1.6 on 2025-03-10 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0008_alter_followrequest_actor_alter_followrequest_target'),
        ('socialnetwork', '0008_remove_author_github_url_author_profile_image'),
    ]

    operations = [
    ]
