# Generated by Django 5.1.6 on 2025-03-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0009_merge_20250310_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmediabased',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hosted_images/'),
        ),
    ]
