# Generated by Django 5.1.6 on 2025-02-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_hostedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostedImage',
        ),
    ]
