# Generated by Django 5.1.6 on 2025-02-16 20:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('following', models.ManyToManyField(related_name='followers', to='socialnetwork.author')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteAuthor',
            fields=[
                ('author_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialnetwork.author')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=50)),
            ],
            bases=('socialnetwork.author',),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visibility_type', models.CharField(choices=[('PU', 'Public'), ('UN', 'Unlisted'), ('FO', 'Friends-Only')], default='PU', max_length=2)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(default=None, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socialnetwork.author')),
                ('is_in_private_inbox_of', models.ManyToManyField(blank=True, related_name='%(class)s_private_inbox', to='socialnetwork.author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostMarkdown',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visibility_type', models.CharField(choices=[('PU', 'Public'), ('UN', 'Unlisted'), ('FO', 'Friends-Only')], default='PU', max_length=2)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(default=None, null=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socialnetwork.author')),
                ('is_in_private_inbox_of', models.ManyToManyField(blank=True, related_name='%(class)s_private_inbox', to='socialnetwork.author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostPlainText',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visibility_type', models.CharField(choices=[('PU', 'Public'), ('UN', 'Unlisted'), ('FO', 'Friends-Only')], default='PU', max_length=2)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(default=None, null=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socialnetwork.author')),
                ('is_in_private_inbox_of', models.ManyToManyField(blank=True, related_name='%(class)s_private_inbox', to='socialnetwork.author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalAuthor',
            fields=[
                ('author_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialnetwork.author')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('socialnetwork.author',),
        ),
    ]
