# Generated by Django 5.1.6 on 2025-02-21 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmediabased',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socialnetwork.localauthor'),
        ),
        migrations.AlterField(
            model_name='posttextbased',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socialnetwork.localauthor'),
        ),
    ]
