# Generated by Django 5.1.6 on 2025-02-21 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmediabased',
            old_name='_author',
            new_name='base_author',
        ),
        migrations.RenameField(
            model_name='posttextbased',
            old_name='_author',
            new_name='base_author',
        ),
    ]
