# Generated by Django 5.1.6 on 2025-02-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0002_rename__author_postmediabased_base_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
