# Generated by Django 5.1.6 on 2025-02-22 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0003_author_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmediabased',
            name='base_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='socialnetwork.author'),
        ),
        migrations.AlterField(
            model_name='posttextbased',
            name='base_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='socialnetwork.author'),
        ),
    ]
