# Generated by Django 5.1.6 on 2025-03-05 01:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0006_remove_remoteauthor_remote_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('comment_type', models.CharField(choices=[('PT', 'Plain Text'), ('MD', 'Markdown')], default='PT', max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.author')),
            ],
        ),
        migrations.CreateModel(
            name='PostDifferentiator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_post_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.postmediabased')),
                ('_post_text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.posttextbased')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.author')),
                ('target_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.comment')),
                ('target_post_differentiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.postdifferentiator')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='_post_differentiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.postdifferentiator'),
        ),
    ]
