# Generated by Django 5.1.6 on 2025-03-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0007_comment_postdifferentiator_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='github_url',
        ),
        migrations.AddField(
            model_name='author',
            name='profile_image',
            field=models.URLField(blank=True),
        ),
    ]
