# Generated by Django 5.1.6 on 2025-03-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0007_comment_postdifferentiator_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttextbased',
            name='title',
            field=models.CharField(default='Untitled Post', max_length=255),
        ),
    ]
