"""Tests for node2node likes"""
from django.urls import reverse

from rest_framework import status

from core.utils.testing_utils import Node2NodeReceptionTestCase

from posts.models import Post, PostTypes, VisibilityTypes
from comments.models import Comment
from user_management.models import Node, User, Author, JoinRequest
from likes.models import Like

import requests

import json


class TestNode2NodeLikes(Node2NodeReceptionTestCase):
    def setUp(self) -> None:
        super().setUp()
        # create a user, and post+comment to like on
        self.initialize_sample_authors(3)
        self.initialize_sample_text_posts(1)
        # self.comment is written by author 0 on author 1's post

        self.comment = Comment.objects.create_comment(
            author=self.sample_authors[0],
            post=self.sample_posts[1][0],
            content="hello",
            content_type=PostTypes.PLAINTEXT
        )

        self.initialize_other_node()
        self.initialize_external_authors(1)

        self.author0_inbox_url = self.live_server_url + reverse("user_management:node2node_inbox", args=[
            self.sample_authors[0].uuid
        ])

    def test_create_like_on_post(self) -> None:
        """simulate receiving a like on a post"""
        post = self.sample_posts[0][0]
        external_author = self.external_authors[0]

        receive_json = {
            "type": "like",
            "author": {
                "type": "author",
                "id": external_author.fqid,
                "host": self.other_node.get_host_url_slash(),
                "displayName": external_author.display_name,
                "profileImage": "",
                "page": "http://localhost:10000/api/authors/3f3c2376-c0eb-401e-abd9-3a1ab6c5cfca",  # This shouldn't matter?
            },
            "published": "2025-03-29T22:22:35.342617+00:00",
            # ID is generated by the remote node
            "id": "http://localhost:10000/apilikes/5f4b580c-bd90-4ba1-a132-3826d3d50dec",
            "object": post.fqid,
        }
        receive_json_string = json.dumps(receive_json)
        response = requests.post(self.author0_inbox_url, data=receive_json_string, headers={"Content-Type": "application/json"},
                                 auth=(self.other_node_user.username, "node"))
        # check that the like was created
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Like.objects.count(), 1)
        like = Like.objects.get()
        self.assertEqual(like.target, post)
        self.assertEqual(like.author, external_author)

    def test_create_like_on_comment(self) -> None:
        """simulate receiving a like on a comment"""
        post = self.sample_posts[0][0]
        external_author = self.external_authors[0]

        receive_json = {
            "type": "like",
            "author": {
                "type": "author",
                "id": external_author.fqid,
                "host": self.other_node.get_host_url_slash(),
                "displayName": external_author.display_name,
                "profileImage": "",
                "page": "http://localhost:10000/api/authors/3f3c2376-c0eb-401e-abd9-3a1ab6c5cfca",  # This shouldn't matter?
            },
            "published": "2025-03-29T22:22:35.342617+00:00",
            # ID is generated by the remote node
            "id": "http://localhost:10000/apilikes/5f4b580c-bd90-4ba1-a132-3826d3d50dec",
            "object": self.comment.fqid,
        }
        receive_json_string = json.dumps(receive_json)
        response = requests.post(self.author0_inbox_url, data=receive_json_string, headers={"Content-Type": "application/json"},
                                 auth=(self.other_node_user.username, "node"))
        # check that the like was created
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Like.objects.count(), 1)
        like = Like.objects.get()
        self.assertEqual(like.target, self.comment)
        self.assertEqual(like.author, external_author)

    def test_create_like_unauthorized(self) -> None:
        """simulate receiving a like on a post, but with bad auth and no auth"""
        post = self.sample_posts[0][0]
        external_author = self.external_authors[0]

        receive_json = {
            "type": "like",
            "author": {
                "type": "author",
                "id": external_author.fqid,
                "host": self.other_node.get_host_url_slash(),
                "displayName": external_author.display_name,
                "profileImage": "",
                "page": "http://localhost:10000/api/authors/3f3c2376-c0eb-401e-abd9-3a1ab6c5cfca",  # This shouldn't matter?
            },
            "published": "2025-03-29T22:22:35.342617+00:00",
            # ID is generated by the remote node
            "id": "http://localhost:10000/apilikes/5f4b580c-bd90-4ba1-a132-3826d3d50dec",
            "object": post.fqid,
        }
        receive_json_string = json.dumps(receive_json)
        # test with bad auth
        response = requests.post(self.author0_inbox_url, data=receive_json_string, headers={"Content-Type": "application/json"},
                                 auth=(self.other_node_user.username, "badpassword"))
        # make sure we get a 403/401 and the like is not created
        self.assertIn(response.status_code, [
                      status.HTTP_403_FORBIDDEN, status.HTTP_401_UNAUTHORIZED])
        self.assertEqual(Like.objects.count(), 0)

        # test with no auth
        response = requests.post(self.author0_inbox_url, data=receive_json_string, headers={
                                 "Content-Type": "application/json"})
        # make sure we get a 403/401 and the like is not created
        self.assertIn(response.status_code, [
                      status.HTTP_403_FORBIDDEN, status.HTTP_401_UNAUTHORIZED])
        self.assertEqual(Like.objects.count(), 0)

    def test_create_like_bad_format(self) -> None:
        """Simulate receiving a badly formatted like"""

        receive_json = {
            "type": "like",
            "author": {
                "type": "author",
                "something": "incorrect",
            },
            "published": "wrong format here",
        }
        receive_json_string = json.dumps(receive_json)
        response = requests.post(self.author0_inbox_url, data=receive_json_string, headers={"Content-Type": "application/json"},
                                 auth=(self.other_node_user.username, "node"))
        # make sure we get a 400 and the like is not created
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertEqual(Like.objects.count(), 0)
