# Generated by Django 5.1.6 on 2025-03-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_rename_owner_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.CharField(choices=[('PT', 'Plain Text'), ('MD', 'Markdown'), ('IMG', 'Image'), ('VID', 'Video')], default='PT', max_length=3, verbose_name='Content type'),
        ),
    ]
