from __future__ import annotations

from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from comments.models import Comment
    from likes.models import Like

from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _

from user_management.models import Author
from core.utils.api_object import ApiObject, ApiObjectManager

# === These are enums for the types of posts ===


class PostTypes(models.TextChoices):
    PLAINTEXT = "PT", _("Plain Text")
    MARKDOWN = "MD", _("Markdown")
    IMAGE = "IMG", _("Image")
    VIDEO = "VID", _("Video")


class VisibilityTypes(models.TextChoices):
    PUBLIC = "PB", _("Public")
    FRIENDS_ONLY = "FO", _("Friends Only")
    UNLISTED = "UL", _("Unlisted")

# === These are actual models ===


class PostManager(ApiObjectManager["Post"]):
    def get_typed_post(self, type: PostTypes, include_deleted: bool = False) -> models.QuerySet[Post]:
        return self.get_queryset().filter(post_type=type)

    def create(self, *args: Any, **kwargs: Any) -> Post:
        if 'post_type' not in kwargs:
            raise ValidationError("Post type must be specified")
        if 'fqid' in kwargs:
            raise ValidationError("fqid must be generated by the model")
        return super().create(*args, **kwargs)

    def create_post(self, author: Author, title: str, description: str, content: str, post_type: PostTypes, visibility_type: VisibilityTypes) -> Post:
        return self.create(host_node=author.host_node, author=author, title=title, description=description, content=content, post_type=post_type, visibility_type=visibility_type)

    @property
    def plaintext(self) -> models.QuerySet[Post]:
        return self.get_typed_post(PostTypes.PLAINTEXT)

    @property
    def markdown(self) -> models.QuerySet[Post]:
        return self.get_typed_post(PostTypes.MARKDOWN)

    @property
    def image(self) -> models.QuerySet[Post]:
        return self.get_typed_post(PostTypes.IMAGE)

    @property
    def video(self) -> models.QuerySet[Post]:
        return self.get_typed_post(PostTypes.VIDEO)


class DeletedPostManager(PostManager):
    """Deleted posts are posts that are soft-deleted, only an admin should be able to see these"""

    def get_queryset(self) -> models.QuerySet[Post]:
        return super().get_queryset().filter(is_soft_deleted=True)


class VisiblePostManager(PostManager):
    """Visible posts are posts that are not soft-deleted"""

    def get_queryset(self) -> models.QuerySet[Post]:
        return super().get_queryset().filter(is_soft_deleted=False)


class Post(ApiObject):
    """
    A post is either a text post or a media post. Don't use this model directly, but use TextPost or MediaPost instead (proxy models).
    Text posts' content is the text of the post
        A text post must have a _text_type field set
    Media posts' content is a URL to the media file
        A media post must have a _media_type field set
    """
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True)
    content = models.TextField()

    post_type = models.CharField(
        max_length=4, choices=PostTypes.choices, default=PostTypes.PLAINTEXT
    )

    visibility_type = models.CharField(
        max_length=2, choices=VisibilityTypes.choices, default=VisibilityTypes.PUBLIC
    )

    is_soft_deleted = models.BooleanField(default=False)

    author: models.ForeignKey[Author, Author] = models.ForeignKey(
        Author, on_delete=models.CASCADE, related_name='posts')

    if TYPE_CHECKING:
        comments: models.QuerySet[Comment]
        likes: models.QuerySet[Like]

    # managers
    objects: PostManager = PostManager()
    deleted_posts = DeletedPostManager()
    visible_posts = VisiblePostManager()

    def __str__(self) -> str:
        return f"{self.title} ({self.post_type}) by {self.author.display_name}"

    # soft deletion related methods
    def soft_delete(self) -> None:
        """Soft-delete this post (it will be hidden from anyone except administrators)"""
        if self.is_soft_deleted:
            raise ValidationError("Post is already soft-deleted")
        self.is_soft_deleted = True
        self.save()

    def restore(self) -> None:
        """Restore this post from soft-deletion"""
        if not self.is_soft_deleted:
            raise ValidationError("Post is not soft-deleted")
        self.is_soft_deleted = False
        self.save()

    def generate_fqid(self) -> str:
        return f"{self.host_node.host_url}/posts/{self.uuid}"  # TODO replace with reverse() call :)
