from __future__ import annotations

import os
import tempfile
from typing import Any, TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from comments.models import Comment
    from likes.models import Like
    from user_management.models import Node

from django.urls import reverse
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q
from django.utils.translation import gettext_lazy as _
from django.core.validators import URLValidator

from user_management.models import Author
from core.utils.api_object import ApiObjectManager, AuthoredApiObject
from core.utils.validators import validate_url_returns_image
from moviepy.editor import VideoFileClip


# === These are enums for the types of posts ===


class PostTypes(models.TextChoices):
    PLAINTEXT = "PT", _("Plain Text")
    MARKDOWN = "MD", _("Markdown")
    IMAGE = "IMG", _("Image")
    VIDEO = "VID", _("Video")


# These are for mapping from the web content type to the post type
CONTENT_TYPE_WEB_MAP: dict[str, str] = {
    PostTypes.PLAINTEXT: "text/plain",
    PostTypes.MARKDOWN: "text/markdown",
    # check back on this
    PostTypes.IMAGE: "image/png;base64",
    # this isn't implemented yet
    PostTypes.VIDEO: "video/mp4;base64",
}

CONTENT_TYPE_WEB_MAP_REVERSE: dict[str, str] = {
    "text/plain": PostTypes.PLAINTEXT,
    "text/markdown": PostTypes.MARKDOWN,
    "image/png;base64": PostTypes.IMAGE,
    "image/jpeg;base64": PostTypes.IMAGE,
    "video/mp4;base64": PostTypes.VIDEO,
}


class VisibilityTypes(models.TextChoices):
    PUBLIC = "PB", _("Public")
    FRIENDS_ONLY = "FO", _("Friends Only")
    UNLISTED = "UL", _("Unlisted")
    DELETED = "DL", _("Deleted")


# There are for mapping from web `visibility` field to the visibility type
VISIBILITY_TYPE_WEB_MAP: dict[str, str] = {
    VisibilityTypes.PUBLIC: "PUBLIC",
    VisibilityTypes.FRIENDS_ONLY: "FRIENDS",
    VisibilityTypes.UNLISTED: "UNLISTED",
}

VISIBILITY_TYPE_WEB_MAP_REVERSE: dict[str, str] = {
    "PUBLIC": VisibilityTypes.PUBLIC,
    "FRIENDS": VisibilityTypes.FRIENDS_ONLY,
    "UNLISTED": VisibilityTypes.UNLISTED,
}


class VisibilityTypeResolver:
    """Modified an existing Q object with a visibility type"""
    @staticmethod
    def modify_q(existing_q: Q, visibility_type: VisibilityTypes, author: Optional[Author]) -> Q:
        query_filter = Q()
        match visibility_type:
            case VisibilityTypes.PUBLIC:
                query_filter = existing_q | Q(visibility_type=VisibilityTypes.PUBLIC)
            case VisibilityTypes.FRIENDS_ONLY:
                if author == None:
                    query_filter = existing_q
                query_filter = existing_q | (Q(visibility_type=VisibilityTypes.FRIENDS_ONLY) & Q(
                    author__followers__in=[author]) & Q(author__following__in=[author]))
            case VisibilityTypes.UNLISTED:
                query_filter = existing_q | Q(visibility_type=VisibilityTypes.UNLISTED)
            case _:
                raise ValueError("Invalid visibility type")
        if query_filter != Q():
            # Remove disabled nodes from being visible
            query_filter = query_filter & Q(author__host_node__is_disabled=False)
        return query_filter


# === These are actual models ===


class PostManager(ApiObjectManager["Post"]):

    def get_queryset(self) -> models.QuerySet[Post]:
        """Fetch only non-deleted posts by default."""
        return super().get_queryset()  # don't filter these, use post.visible_posts to get only visible posts

    # filtering by post type
    @property
    def plaintext(self) -> models.QuerySet[Post]:
        """Retrieve all plaintext posts"""
        return self.get_queryset().filter(post_type=PostTypes.PLAINTEXT)

    @property
    def markdown(self) -> models.QuerySet[Post]:
        """Retrieve all markdown posts"""
        return self.get_queryset().filter(post_type=PostTypes.MARKDOWN)

    @property
    def image(self) -> models.QuerySet[Post]:
        """Retrieve all image posts"""
        return self.get_queryset().filter(post_type=PostTypes.IMAGE)

    @property
    def video(self) -> models.QuerySet[Post]:
        """Retrieve all video posts"""
        return self.get_queryset().filter(post_type=PostTypes.VIDEO)

    def get_typed_posts(self, type: PostTypes, include_deleted: bool = False) -> models.QuerySet[Post]:
        return self.get_queryset().filter(post_type=type)

    def create(self, *args: Any, **kwargs: Any) -> Post:
        if 'post_type' not in kwargs:
            raise ValidationError("Post type must be specified")
        # if 'fqid' in kwargs and 'host_node' not in kwargs:
        #     raise ValidationError("fqid must be generated by the model")
        return super().create(*args, **kwargs)

    def create_post(
        self,
        author: Author,
        title: str,
        description: str,
        content: str,
        post_type: PostTypes,
        visibility_type: VisibilityTypes
    ) -> Post:
        """Creates a post using validated arguments."""
        return self.create(
            host_node=author.host_node,
            author=author,
            title=title,
            description=description,
            content=content,
            post_type=post_type,
            visibility_type=visibility_type
        )


class DeletedPostManager(PostManager):
    """Deleted posts are posts that are soft-deleted, only an admin should be able to see these"""

    def get_queryset(self) -> models.QuerySet[Post]:
        return super().get_queryset().filter(is_soft_deleted=True)

    def create_post(self, author: Author, title: str, description: str, content: str, post_type: PostTypes, visibility_type: VisibilityTypes) -> Post:
        raise ValidationError(
            "Cannot create a post in the deleted posts manager")


class VisiblePostManager(PostManager):
    """Visible posts are posts that are not soft-deleted"""

    def get_queryset(self) -> models.QuerySet[Post]:
        return super().get_queryset().filter(is_soft_deleted=False)

    def get_posts_visible_to_author(self, author: Optional[Author]) -> models.QuerySet[Post]:
        """Get all the posts that an author is allowed to see (either in stream or by a direct link)"""
        # we don't have to worry about deleted posts because of self.get_queryset()
        # see the visibility User stories: https://uofa-cmput404.github.io/general/project.html#user-stories
        query = Q()  # start with an empty query
        for visibility_type in VisibilityTypes:  # add up every visibility type's query
            query = VisibilityTypeResolver.modify_q(query, visibility_type, author)

        # also, always show your own posts
        query = query | Q(author=author, is_soft_deleted=False)

        return self.get_queryset().filter(query)

    def get_posts_in_stream_of_author(self, author: Author, paginate_start: int, paginate_count: int) -> models.QuerySet[Post]:
        """Get all the posts that are in the stream of an author"""
        base_queryset = self.get_posts_visible_to_author(author)
        query_filter = Q()
        # now filter them down to only the ones that are in the stream
        # unlisted posts should only be in the stream of followers
        remove_unlisted_nonfollowing = Q(visibility_type=VisibilityTypes.UNLISTED) & ~Q(
            author__followers__in=[author]) & ~Q(author=author)
        query_filter = query_filter | ~remove_unlisted_nonfollowing

        # still, your own posts are always in your stream
        query_filter = query_filter | Q(author=author)
        # slicing an un-fetched queryset reduces the database load :)
        return base_queryset.filter(query_filter).distinct().order_by('-created_at')[paginate_start:paginate_start + paginate_count]


class Post(AuthoredApiObject):
    """
    A post is either a text post or a media post. Don't use this model directly, but use TextPost or MediaPost instead (proxy models).
    Text posts' content is the text of the post
        A text post must have a _text_type field set
    Media posts' content is a URL to the media file
        A media post must have a _media_type field set
    """
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True)
    content = models.TextField(null=True, blank=True)

    post_type: models.CharField[str, str] = models.CharField(
        max_length=4, choices=PostTypes.choices, default=PostTypes.PLAINTEXT
    )

    visibility_type = models.CharField(
        max_length=2, choices=VisibilityTypes.choices, default=VisibilityTypes.PUBLIC
    )

    is_soft_deleted = models.BooleanField(default=False)

    author: models.ForeignKey[Author, Author] = models.ForeignKey(
        Author, on_delete=models.CASCADE, related_name='all_posts')

    image: models.ImageField = models.ImageField(upload_to="post_images/", null=True, blank=True)

    video: models.FileField = models.FileField(
        upload_to="post_videos/",
        null=True,
        blank=True,
        help_text="Video must be shorter than 4 seconds",
    )

    if TYPE_CHECKING:
        comments: models.QuerySet[Comment]
        likes: models.QuerySet[Like]

    # managers
    objects: PostManager = PostManager()
    deleted_posts = DeletedPostManager()
    visible_posts = VisiblePostManager()

    def __str__(self) -> str:
        return f"{self.title} ({self.post_type}) by {self.author.display_name}"

    # soft deletion related methods
    def soft_delete(self) -> None:
        """Soft-delete this post (it will be hidden from anyone except administrators)"""
        if self.is_soft_deleted:
            raise ValidationError("Post is already soft-deleted")
        self.is_soft_deleted = True
        self.visibility_type = VisibilityTypes.DELETED
        self.save()

    def restore(self) -> None:
        """Restore this post from soft-deletion"""
        if not self.is_soft_deleted:
            raise ValidationError("Post is not soft-deleted")
        self.is_soft_deleted = False
        self.visibility_type = VisibilityTypes.UNLISTED
        self.save()

    def generate_fqid(self) -> str:
        return (self.host_node.host_url + reverse('user_management:node2node_authors_posts-detail', kwargs={'post_uuid': self.uuid, 'author_uuid': self.author.uuid})).replace("/api/api", "/api")

    def get_absolute_url(self) -> str:
        if self.visibility_type == VisibilityTypes.FRIENDS_ONLY:
            raise ValidationError("Friends-only posts do not have shareable links")
        if self.host_node.is_local_node:
            return self.host_node.host_site_url+reverse('posts:view_post', kwargs={'post_uuid': self.uuid})
        else:
            return self.generate_fqid()

    def check_can_be_seen_by(self, viewer: Author) -> bool:
        """Check if this post is possible to be seen by the viewer (either in stream or via a direct link)

        **Warning: this is a relatively expensive operation**

        Args:
            viewer (Author): The author who is trying to view the post

        Returns:
            bool: True if the viewer can see the post, False otherwise
        """
        return Post.visible_posts.get_posts_visible_to_author(viewer).filter(uuid=self.uuid).exists()

    def clean(self) -> None:
        if self.post_type in [PostTypes.PLAINTEXT, PostTypes.MARKDOWN]:
            # make sure the content is the only non-null field
            if not self.content:
                raise ValidationError("Content must be specified")
            if self.image:
                raise ValidationError("Image field must be empty for plaintext and markdown posts")
            if self.video:
                raise ValidationError("Video field must be empty for plaintext and markdown posts")
        elif self.post_type == PostTypes.IMAGE:
            # make sure the image field is the only non-null field
            if not self.image:
                raise ValidationError("Image must be specified")
            if self.content:
                raise ValidationError("Content field must be empty for image posts")
            if self.video:
                raise ValidationError("Video field must be empty for image posts")
        elif self.post_type == PostTypes.VIDEO:
            # make sure the video field is the only non-null field
            if not self.video:
                raise ValidationError("Video must be specified")
            if self.content:
                raise ValidationError("Content field must be empty for video posts")
            if self.image:
                raise ValidationError("Image field must be empty for video posts")

            # validate the video duration
            video = None
            temp_video_path = ""
            with tempfile.NamedTemporaryFile(delete=False) as temp_file:
                for chunk in self.video.chunks():
                    temp_file.write(chunk)
                temp_video_path = temp_file.name

            try:
                video = VideoFileClip(temp_video_path)
                if video.duration > 4.0:
                    raise ValidationError("Video must be 4 seconds or shorter")
            except (IOError, OSError) as e:
                raise ValidationError(f"Could not read video file: {str(e)}")
            finally:
                if video is not None:
                    video.close()
                if temp_video_path and os.path.exists(temp_video_path):
                    os.remove(temp_video_path)
        super().clean()

    # https://stackoverflow.com/a/8342249
    def save(self, *args: Any, **kwargs: Any) -> None:
        """Clears the old image if it exists before saving"""
        try:
            this = Post.objects.get(uuid=self.uuid)
            if this.image != self.image:
                this.image.delete(save=False)
        except:
            pass
        super(Post, self).save(*args, **kwargs)

    def delete(self, *args: Any, **kwargs: Any) -> tuple[int, dict[str, Any]]:
        """Deletes the image before deleting the post, only for hard deletion. Soft-deletion
        does not delete images."""
        self.image.delete()
        return super(Post, self).delete(*args, **kwargs)

    def get_template_name(self) -> str:
        """Get the template name for this post's inner-content"""
        # will return, for example "components/post_inner_content/PT.html" for a plaintext post
        # each inner-content template can be customized based on what kind of content it is
        return f"components/post_inner_content/{self.post_type}.html"

    def node2node_encode_as_class_json_dict(self) -> dict[str, Any]:
        from posts.serializers import PostSerializer
        return PostSerializer().to_representation(self)

    def _propagate_post_save_to_other_nodes(self, created: bool) -> None:
        for follower in self.author.followers.all():
            if follower.is_local:
                continue
            # send the post to the follower's inbox
            if created:
                url = self.node2node_get_creation_url(author_for_inbox=follower)
            else:
                url = self.node2node_get_update_url(author_for_inbox=follower)
            follower.host_node.send_create(
                self.node2node_encode_as_class_json_dict(),
                to=url,
            )

    def _propagate_deletion_to_other_nodes(self) -> None:
        for follower in self.author.followers.all():
            if follower.is_local:
                continue
            # send the post to the follower's inbox
            url = self.node2node_get_deletion_url(author_for_inbox=follower)
            follower.host_node.send_delete(
                url,
            )

    def node2node_get_creation_url(self, author_for_inbox: Optional[Author] = None) -> str:
        # the _propagate_save_to_other_nodes method will handle this as it needs some custom logic
        if author_for_inbox is None:
            return reverse("posts:node2node_posts-list")
        return author_for_inbox.node2node_get_inbox_url()

    def node2node_get_update_url(self, author_for_inbox: Optional[Author] = None) -> str:
        return self.node2node_get_creation_url(author_for_inbox=author_for_inbox)
        # return reverse("posts:api_posts-detail", kwargs={"fqid": self.get_encoded_fqid()})

    def node2node_get_deletion_url(self, author_for_inbox: Optional[Author] = None) -> str:
        return self.node2node_get_update_url(author_for_inbox=author_for_inbox)

    @property
    def markdown_image_link(self) -> str | None:
        """
        Returns a MD img link for the uploaded image, if present.
        expl of this: ![title](http://127.0.0.1:8000/media/post_images/abc.png)
        """
        if self.post_type != PostTypes.IMAGE:
            raise ValidationError("This post is not an image post")
        assert self.image is not None
        return f"![{self.title}]({self.image.url})"

    @property
    def markdown_video_link(self) -> str | None:
        """
        Returns markdown link for video, similar to image link
        Example: ![title](http://127.0.0.1:8000/media/post_videos/abc.mp4)
        """
        if self.post_type != PostTypes.VIDEO:
            raise ValidationError("This post is not a video post")
        assert self.video is not None
        return f"<video alt='{self.title}' src='{self.video.url}' controls>"
