from __future__ import annotations

from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from comments.models import Comment
    from likes.models import Like
    from user_management.models import Node

from django.urls import reverse
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q
from django.utils.translation import gettext_lazy as _
from django.core.validators import URLValidator

from user_management.models import Author
from core.utils.api_object import ApiObjectManager, AuthoredApiObject
from core.utils.validators import validate_url_returns_image


# === These are enums for the types of posts ===


class PostTypes(models.TextChoices):
    PLAINTEXT = "PT", _("Plain Text")
    MARKDOWN = "MD", _("Markdown")
    IMAGE = "IMG", _("Image")
    VIDEO = "VID", _("Video")


# These are for mapping from the web content type to the post type
CONTENT_TYPE_WEB_MAP: dict[str, str] = {
    PostTypes.PLAINTEXT: "text/plain",
    PostTypes.MARKDOWN: "text/markdown",
    # check back on this
    PostTypes.IMAGE: "image/png;base64",
    # this isn't implemented yet
    PostTypes.VIDEO: "application/base64"
}

CONTENT_TYPE_WEB_MAP_REVERSE: dict[str, str] = {
    "text/plain": PostTypes.PLAINTEXT,
    "text/markdown": PostTypes.MARKDOWN,
    "image/png;base64": PostTypes.IMAGE,
    "image/jpeg;base64": PostTypes.IMAGE,
    "application/base64": PostTypes.VIDEO,
}


class VisibilityTypes(models.TextChoices):
    PUBLIC = "PB", _("Public")
    FRIENDS_ONLY = "FO", _("Friends Only")
    UNLISTED = "UL", _("Unlisted")


class VisibilityTypeResolver:
    """Modified an existing Q object with a visibility type"""
    @staticmethod
    def modify_q(existing_q: Q, visibility_type: VisibilityTypes, author: Author) -> Q:
        match visibility_type:
            case VisibilityTypes.PUBLIC:
                return existing_q | Q(visibility_type=VisibilityTypes.PUBLIC)
            case VisibilityTypes.FRIENDS_ONLY:
                return existing_q | (Q(visibility_type=VisibilityTypes.FRIENDS_ONLY) & Q(
                    author__followers__in=[author]) & Q(author__following__in=[author]))
            case VisibilityTypes.UNLISTED:
                return existing_q | Q(visibility_type=VisibilityTypes.UNLISTED)
            case _:
                raise ValueError("Invalid visibility type")


# === These are actual models ===


class PostManager(ApiObjectManager["Post"]):

    def get_queryset(self) -> models.QuerySet[Post]:
        """Fetch only non-deleted posts by default."""
        return super().get_queryset()  # don't filter these, use post.visible_posts to get only visible posts

    # filtering by post type
    @property
    def plaintext(self) -> models.QuerySet[Post]:
        """Retrieve all plaintext posts"""
        return self.get_queryset().filter(post_type=PostTypes.PLAINTEXT)

    @property
    def markdown(self) -> models.QuerySet[Post]:
        """Retrieve all markdown posts"""
        return self.get_queryset().filter(post_type=PostTypes.MARKDOWN)

    @property
    def image(self) -> models.QuerySet[Post]:
        """Retrieve all image posts"""
        return self.get_queryset().filter(post_type=PostTypes.IMAGE)

    @property
    def video(self) -> models.QuerySet[Post]:
        """Retrieve all video posts"""
        return self.get_queryset().filter(post_type=PostTypes.VIDEO)

    def get_typed_posts(self, type: PostTypes, include_deleted: bool = False) -> models.QuerySet[Post]:
        return self.get_queryset().filter(post_type=type)

    def create(self, *args: Any, **kwargs: Any) -> Post:
        if 'post_type' not in kwargs:
            raise ValidationError("Post type must be specified")
        if 'fqid' in kwargs:
            raise ValidationError("fqid must be generated by the model")
        return super().create(*args, **kwargs)

    def create_post(
        self,
        author: Author,
        title: str,
        description: str,
        content: str,
        post_type: PostTypes,
        visibility_type: VisibilityTypes
    ) -> Post:
        """Creates a post using validated arguments."""
        return self.create(
            host_node=author.host_node,
            author=author,
            title=title,
            description=description,
            content=content,
            post_type=post_type,
            visibility_type=visibility_type
        )


class DeletedPostManager(PostManager):
    """Deleted posts are posts that are soft-deleted, only an admin should be able to see these"""

    def get_queryset(self) -> models.QuerySet[Post]:
        return super().get_queryset().filter(is_soft_deleted=True)

    def create_post(self, author: Author, title: str, description: str, content: str, post_type: PostTypes, visibility_type: VisibilityTypes) -> Post:
        raise ValidationError(
            "Cannot create a post in the deleted posts manager")


class VisiblePostManager(PostManager):
    """Visible posts are posts that are not soft-deleted"""

    def get_queryset(self) -> models.QuerySet[Post]:
        return super().get_queryset().filter(is_soft_deleted=False)

    def get_posts_visible_to_author(self, author: Author) -> models.QuerySet[Post]:
        """Get all the posts that an author is allowed to see (either in stream or by a direct link)"""
        # we don't have to worry about deleted posts because of self.get_queryset()
        # see the visibility User stories: https://uofa-cmput404.github.io/general/project.html#user-stories
        query = Q()  # start with an empty query
        for visibility_type in VisibilityTypes:  # add up every visibility type's query
            query = VisibilityTypeResolver.modify_q(query, visibility_type, author)

        # also, always show your own posts
        query = query | Q(author=author, is_soft_deleted=False)

        return self.get_queryset().filter(query)

    def get_posts_in_stream_of_author(self, author: Author, paginate_start: int, paginate_count: int) -> models.QuerySet[Post]:
        """Get all the posts that are in the stream of an author"""
        base_queryset = self.get_posts_visible_to_author(author)
        query_filter = Q()
        # now filter them down to only the ones that are in the stream
        # unlisted posts should only be in the stream of followers
        remove_unlisted_nonfollowing = Q(visibility_type=VisibilityTypes.UNLISTED) & ~Q(
            author__followers__in=[author]) & ~Q(author=author)
        query_filter = query_filter | ~remove_unlisted_nonfollowing

        # still, your own posts are always in your stream
        query_filter = query_filter | Q(author=author)
        # slicing an un-fetched queryset reduces the database load :)
        return base_queryset.filter(query_filter).order_by('-created_at')[paginate_start:paginate_start + paginate_count]


class Post(AuthoredApiObject):
    """
    A post is either a text post or a media post. Don't use this model directly, but use TextPost or MediaPost instead (proxy models).
    Text posts' content is the text of the post
        A text post must have a _text_type field set
    Media posts' content is a URL to the media file
        A media post must have a _media_type field set
    """
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True)
    content = models.TextField()

    post_type: models.CharField[str, str] = models.CharField(
        max_length=4, choices=PostTypes.choices, default=PostTypes.PLAINTEXT
    )

    visibility_type = models.CharField(
        max_length=2, choices=VisibilityTypes.choices, default=VisibilityTypes.PUBLIC
    )

    is_soft_deleted = models.BooleanField(default=False)

    author: models.ForeignKey[Author, Author] = models.ForeignKey(
        Author, on_delete=models.CASCADE, related_name='all_posts')

    if TYPE_CHECKING:
        comments: models.QuerySet[Comment]
        likes: models.QuerySet[Like]

    # managers
    objects: PostManager = PostManager()
    deleted_posts = DeletedPostManager()
    visible_posts = VisiblePostManager()

    def __str__(self) -> str:
        return f"{self.title} ({self.post_type}) by {self.author.display_name}"

    # soft deletion related methods
    def soft_delete(self) -> None:
        """Soft-delete this post (it will be hidden from anyone except administrators)"""
        if self.is_soft_deleted:
            raise ValidationError("Post is already soft-deleted")
        self.is_soft_deleted = True
        self.save()

    def restore(self) -> None:
        """Restore this post from soft-deletion"""
        if not self.is_soft_deleted:
            raise ValidationError("Post is not soft-deleted")
        self.is_soft_deleted = False
        self.save()

    def generate_fqid(self) -> str:
        return self.host_node.host_url + reverse('posts:view_post', kwargs={'post_uuid': self.uuid})

    def get_absolute_url(self) -> str:
        if self.host_node.is_local_node:
            return self.host_node.host_site_url+reverse('posts:view_post', kwargs={'post_uuid': self.uuid})
        else:
            return self.generate_fqid()

    def check_can_be_seen_by(self, viewer: Author) -> bool:
        """Check if this post is possible to be seen by the viewer (either in stream or via a direct link)

        **Warning: this is a relatively expensive operation**

        Args:
            viewer (Author): The author who is trying to view the post

        Returns:
            bool: True if the viewer can see the post, False otherwise
        """
        return Post.visible_posts.get_posts_visible_to_author(viewer).filter(uuid=self.uuid).exists()

    def clean(self) -> None:
        if self.post_type in [PostTypes.IMAGE, PostTypes.VIDEO]:
            # if the post type is an image or video, the content must be a URL
            URLValidator()(self.content)
            if self.post_type == PostTypes.IMAGE:
                validate_url_returns_image(self.content)

        super().clean()

    def get_template_name(self) -> str:
        """Get the template name for this post's inner-content"""
        # will return, for example "components/post_inner_content/PT.html" for a plaintext post
        # each inner-content template can be customized based on what kind of content it is
        return f"components/post_inner_content/{self.post_type}.html"

    def node2node_encode_as_class_json_dict(self) -> dict[str, Any]:
        from posts.serializers import PostSerializer
        return PostSerializer().to_representation(self)

    def node2node_get_creation_url(self) -> str:
        return reverse("posts:api_posts-list")

    def node2node_get_update_url(self) -> str:
        return reverse("posts:api_posts-detail", kwargs={"fqid": self.get_encoded_fqid()})

    def node2node_get_deletion_url(self) -> str:
        return self.node2node_get_update_url()
