# Generated by Django 5.1.6 on 2025-03-12 05:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('fqid', models.CharField(blank=True, max_length=255, unique=True, verbose_name='FQID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Edited at')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('post_type', models.CharField(choices=[('PT', 'Plain Text'), ('MD', 'Markdown'), ('IMG', 'Image'), ('VID', 'Video')], default='PT', max_length=4)),
                ('visibility_type', models.CharField(choices=[('PB', 'Public'), ('FO', 'Friends Only'), ('UL', 'Unlisted')], default='PB', max_length=2)),
                ('is_soft_deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
