# Generated by Django 5.1.6 on 2025-03-23 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_author'),
        ('posts', '0003_post_image_alter_post_author'),
    ]

    operations = [
    ]
