# Generated by Django 5.1.6 on 2025-03-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='Video must be shorter than 4 seconds', null=True, upload_to='post_videos/'),
        ),
    ]
