# Generated by Django 5.1.6 on 2025-04-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_visibility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility_type',
            field=models.CharField(choices=[('PB', 'Public'), ('FO', 'Friends Only'), ('UL', 'Unlisted')], default='PB', max_length=2),
        ),
    ]
