
name: Run Django Tests

on:
  pull_request:
    branches: [ "**" ]

jobs:
  django-test:
    name: django testing
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install geckodriver
      uses: browser-actions/setup-geckodriver@latest

    - name: Install dependencies
      run: |
        pip install -r src/requirements.txt
    - name: Install dev dependencies
      run: |
        pip install -r src/requirements-dev.txt
    - name: Collect static files
      run: |
        python src/manage.py collectstatic --noinput
    - name: Run all tests
      run: |
        cd src
        python manage.py test
